### ISSUE TITLE
Editor not respecting value property

### ISSUE THREAD

**Issue by brandonryan** [tinymce/tinymce-react#115]
**What is the current behavior?**
When you update the value on the editor with onEditorChange property, the editor does not respect the value property when it has not changed. (see example)

[codesandbox example](https://codesandbox.io/s/tinymcereact-drzdd)

**What is the expected behavior?**
Editor value should not update unless value property changes. This will bring it more inline with  input element behavior.
In general, if a value is provided to <Editor/> it should behave like a controlled input, if not, then it should behave like an uncontrolled component.

**Comment by SimonFc** [comment]
You're right that this is the expected behavior but it could be difficult to fix. For future reference I'm going to write down what I've found.

The change in the editor itself is going to happen no matter what so what we would need to do is to somehow revert this change.  `<p>12|</p>` -> `<p>123|</p>` -> `<p>12|</p>`

Currently, any new content is set with the [setContent](https://www.tiny.cloud/docs/api/tinymce/tinymce.editor/#setcontent) method. Doing this when a user is focusing the editor could lead to some "stuttering" since the selection would change (among other things), but perhaps we could do this in some other way.

Also, if the change doesn't introduce a need to refresh the tinymce-react component in (a parent component re-renders it something) we wouldn't actually have a chance to reset the value anyway. I could be wrong but it seems like the way React is handling the wrappers for some native elements is outside of the normal flow of things/APIs which are exposed to us. It looks like they always refresh the value after the (in your example with the input element) onChange event handler has run and any changes that has occurred has been flushed.

[ReactDOMComponent.js](https://github.com/facebook/react/blob/849e8328b596ce67720f33d73a1d57108e6de504/packages/react-dom/src/client/ReactDOMComponent.js#L1253)
[ReactGenericBatching.js](https://github.com/facebook/react/blob/1000f6135efba4f8d8ebffedeb7b472f532a8475/packages/legacy-events/ReactGenericBatching.js#L46)

Actually, I think the same thing can be achieved with the undocumented (not public?) ReactDOM.flushSync function. Placing something like following code after [Editor.tsx#L143](https://github.com/tinymce/tinymce-react/blob/36ec434cbb1db11302e2733e0589b8f6c79f1ee6/src/main/ts/components/Editor.tsx#L143) seems to work:
```
ReactDOM.flushSync(() => {
  if (this.props.value !== newContent) {
    editor.setContent(this.props.value);
  }
});
```

Not sure about the performance implications and if this actually is a viable solution though. To be investigated.

**Comment by Vluf** [comment]
I'm using the "controlled component" flow to deny edits that would cause too long a message, but this issue prevents that.
I don't know why controlled behaviour is even documented if it doesn't behave like one :/

**Comment by mattlo** [comment]
added a workaround to ensure the controlled value updates the editor whenever there's a mismatch

b/c the editor inputs (user entering data in TinyMCE) always update first before `onEditorChange` is triggered, you can take advantage of it with a conditional check of the controlled value with the editor's internal value to determine if the controlled value needs to be re-applied or not.

```tsx

export default function RichTextEditor({
  value, onChange
}) {
  const tinyMce = useRef<any>();

  const onInit = useCallback((editor) => {
    tinyMce.current = editor;
  }, [value]);

  // sync tinymce with `value` if externally modified
  useEffect(() => {
    // tinymce isn't a fully controlled component, but luckily inputs entered in
    // are updated before `onChange` is invoked
    // so when this `useEffect` is called, it's already updated and shouldn't re-init
    // if the updated `value` matches what was initially entered
    // .. but it will re-init if the value was changed externally, which is what we want
    if (tinyMce.current && tinyMce.current.getContent() !== value) {
      // update the editor value
      tinyMce.current.setContent(value, {no_events: true});
    }
  }, [value]);

  return (
    <>
      <Editor
        value={value}
        init={{
          oninit: onInit,
          height: 500,
          setup: onInit
        }}
        onEditorChange={onChange}
      />
    </>
  );
}
```

**Comment by edwinvrgs** [comment]
> added a workaround to ensure the controlled value updates the editor whenever there's a mismatch
> 
> b/c the editor inputs (user entering data in TinyMCE) always update first before `onEditorChange` is triggered, you can take advantage of it with a conditional check of the controlled value with the editor's internal value to determine if the controlled value needs to be re-applied or not.
> 
> ```tsx
> export default function RichTextEditor({
>   value, onChange
> }) {
>   const tinyMce = useRef<any>();
> 
>   const onInit = useCallback((editor) => {
>     tinyMce.current = editor;
>   }, [value]);
> 
>   // sync tinymce with `value` if externally modified
>   useEffect(() => {
>     // tinymce isn't a fully controlled component, but luckily inputs entered in
>     // are updated before `onChange` is invoked
>     // so when this `useEffect` is called, it's already updated and shouldn't re-init
>     // if the updated `value` matches what was initially entered
>     // .. but it will re-init if the value was changed externally, which is what we want
>     if (tinyMce.current && tinyMce.current.getContent() !== value) {
>       // update the editor value
>       tinyMce.current.setContent(value, {no_events: true});
>     }
>   }, [value]);
> 
>   return (
>     <Editor
>       value={value}
>       init={{
>         oninit: onInit,
>         height: 500,
>         setup: onInit
>       }}
>       onEditorChange={onChange}
>     />
>   );
> }
> ```

Im testing this solution but not able to make it work. 

First thing is that `tinyMce.current` does not have the `getContent` function, I'm using this instead `tinyMce.current?.value?.target?.rtcInstance?.editor`.

But still having problems with updating the content based on the ref.

**Comment by tiny-james** [comment]
In the latest release 3.11.0 you should be able to remove your workaround as I have removed the check that the value is different to the previous value.

That said we're looking into how to restrict the editor content using an internal plugin as trying to do it externally, like react controlled components do, can allow things like the undo state or the cursor position to be really hard to manage. For example something that tries to limit the characters to a maximum could end up with a undo history item that is larger than the character limit so when you try to undo it immediately overwrites it.

**Comment by tiny-james** [comment]
I had another go at fixing this problem:
https://github.com/tinymce/tinymce-react/pull/241

The PR still needs to go though review but you can try the examples now and let me know if there are any problems.

**Comment by tiny-james** [comment]
Demos here:
https://codesandbox.io/s/tinymcereact-enforced-value-id4qs
https://codesandbox.io/s/tinymcereact-length-restriction-4f7eo

**Comment by tiny-james** [comment]
The 3.12.0 release should fix this issue.
