### ISSUE TITLE
I can't find what I'm looking for: integrations/react.md

### ISSUE THREAD

**Issue by ale917k** [tinymce/tinymce-react#138]
How can I display the wysiwyg content I get returned from the Editor?

I can save the content correctly inside the hook state, only problem is it returns a string with the HTML content. So, if I try to display that string, I obviously get displayed the full content as a string (tags included).

I looked for solutions and found in React I can set the JSX attribute dangerouslySetInnerHTML (https://stackoverflow.com/questions/36104302/how-do-i-convert-a-string-to-jsx). 
Problem with that is the vulnerability with XSS Attacks.

How can I get around this?

Here the question on Stack Overflow: https://stackoverflow.com/questions/62002038/display-tinymce-content-in-react

Code Sample: https://codesandbox.io/s/boring-tharp-zwflu

Thank you in advance.

**Comment by jscasca** [comment]
Hi @ale917k 

You are right. Using `dangerouslySetInnerHTML` should be avoided as much as possible. A way to get around that would be to parse the HTML content string yourself in order to display it. There are some libraries that can help you do that for example `ReactHtmlParser` as used in this codesandbox: https://codesandbox.io/s/vigilant-villani-w1gt5?file=/src/App.js

Let me know if that helps

**Comment by ale917k** [comment]
Much appreciated your help, both of you. 

@jscasca 
It would be nice to have a parser incorporated with TinyMCE for avoiding extra libraries, but so far the solution you provided works perfectly fine.

Thank you!
