### ISSUE TITLE
I can't find what I'm looking for: plugins/link.md

### ISSUE THREAD

**Issue by jainprateekkumar** [tinymce/tinymce-react#157]
Hello,

I am using TinyMCE React in SPFx solution. 

I have added Editor to a panel(office ui fabric) and when i want to add a link, link dialogue will open but the textbox(url, text to display etc) are not clickable. Though when i click on the label(present on top of textbox), the textbox gets selected and then i am able to type in the textbox.

I have given the example for link dialogue but this issue exists for all the dialogue like for image, media plugin etc

In panel, i have already used the below code which were suggested for these issues:
isBlocking
focusTrapZoneProps={focusTrapZoneProps}
onOuterClick={true}

Regards,
Prateek

**Comment by tiny-james** [comment]
Hi jainprateekkumar,

This sounds like a challenging case for us to replicate especially since none of us are familiar with SPFx. 

Are you able to replicate this in the codesandbox?
[https://codesandbox.io/s/6yz4jzrrxw?fontsize=14](https://codesandbox.io/s/6yz4jzrrxw?fontsize=14)

Where did you get the suggestion to use the settings?:
```
isBlocking
focusTrapZoneProps={focusTrapZoneProps}
onOuterClick={true}
```
None of those settings are props for the TinyMCE react component so I assume you must be referring to some SPFx setting?

**Comment by tiny-james** [comment]
I'm closing this issue as "unable to replicate" (without more information) and potentially "out of scope". Without more information I'm unsure if this is a bug report or a request for technical support.

If this is a bug report then please provide a codesandbox link that can demonstrate the issue and clear replication instructions.

Please note that we can not provide more than basic technical support here though if you provide a codesandbox you are more likely to get help. Generally technical support questions should be asked on the [community forum or if you are a paying customer you should open a ticket on our support system](https://support.tiny.cloud/hc/en-us).
