### ISSUE TITLE
编辑器内容达到3584字 再输入 当前页面崩溃 当前版本 3.5.0

### ISSUE THREAD

**Issue by liull89** [tinymce/tinymce-react#158]
请问编辑器内容最多多少  如何加大输入内容？

**Comment by tiny-james** [comment]
Hi liull89,

TinyMCE and the react component have no internal limits on the size of the content so crashes due to content size will depend on the browser and computer used. I was able to edit a document with double the number of words you mentioned with no problems.

I would suggest for large documents that you avoid using it as a controlled component because that will require more computation resources to work well.

If you need more advice please create a replication case using [https://codesandbox.io/s/6yz4jzrrxw?fontsize=14](https://codesandbox.io/s/6yz4jzrrxw?fontsize=14)

---------------------------------------------------------------------------

嗨liull89，

TinyMCE和react组件对内容的大小没有内部限制，因此由于内容大小而导致的崩溃将取决于所使用的浏览器和计算机。 我能够以两倍于您提到的单词数来编辑文档，而没有任何问题。

对于大型文档，我建议您避免将其用作受控组件，因为这将需要更多计算资源才能正常工作。

如果您需要更多建议，请使用 [https://codesandbox.io/s/6yz4jzrrxw?fontsize=14](https://codesandbox.io/s/6yz4jzrrxw?fontsize=14) 创建复制案例

**Comment by gogoinga** [comment]
这个编辑器要收钱的吗？

**Comment by tiny-james** [comment]
TinyMCE is an opensource editor but the company makes money by charging for technical support and premium plugins. There is extensive documentation but it is all in English.

-----------------------------

TinyMCE是一个开源编辑器，但该公司通过收取技术支持和高级插件的费用来赚钱。 有大量的文档，但是都是英文的。

**Comment by tiny-james** [comment]
I'm closing this issue as "can not replicate".

If this bug still occurs please provide a codesandbox and clear replication instructions.

-------------------------
我正在关闭此问题，因为“无法复制”。

如果仍然发生此错误，请提供一个codeandbox并清除复制说明。
