### ISSUE TITLE
How to dispatch event/send signal from a customized plugin & receive from the react component?

### ISSUE THREAD

**Issue by cherishh** [tinymce/tinymce-react#160]
**What is the current behavior?**
I've built a simple customized plugin via Yeoman generator. the plugin looks like this:
```
declare const tinymce: any;

const setup = (editor, url) => {
  editor.ui.registry.addButton('tinymcetest', {
    text: 'tinymcetest button',
    onAction: () => {
      // Note that following is not the actual desired action. I want to dispatch a event or send out a signal, so I can receive this signal in my react component.
      editor.setContent('<p>test</p>');
    }
  });
};

export default () => {
  tinymce.PluginManager.add('tinymcetest', setup);
};
```
But the purpose of this plugin is not change content. I want to send a signal of some sort, so in my react component I can receive it, so that I can show a modal for instance.
But now I can't figure out how to achieve this, how do I send a signal, and how can I receive that signal in my react component?

**What is the expected behavior?**
I can send a signal & can receive it in my react component.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-react`?**
TinyMCE version: 5
browser: Chrome

**Comment by cherishh** [comment]
Found the solution.
In your plugin, you can use `editor.fire(eventName, data)` to dispatch a event.
In your react component, add `init_instance_callback` to your init options:
```
init_instance_callback: function(editor) {
     editor.on('TextColorChange', function(e) {
       console.log('The text color of ' + e.name + ' is now:' + e.color);
     });
     editor.on('yourEventName', function(e) {
       console.log(e);
     });
   }
```

**Comment by tiny-james** [comment]
Hi cherishh,

It looks like you have found the correct solution so I'm going to close this issue.

Due to requiring types we don't currently have a way to register custom event handlers using the react component properties.

One change to your solution which might help in some circumstances is to register the event handler on the setup function:

```jsx
<Editor
      init={{
        setup: function (editor) {
          editor.on("mycustomevent", function (evt) {
            // do something with the event
          });
        }
      }}
    />
```
[Example on codesandbox](https://codesandbox.io/s/tinymcereact-forked-zcisd?file=/src/index.js)

This is needed if you have to capture events that happen during the editor creation.
