### ISSUE TITLE
[Next.js] Uncaught (in promise) TypeError: e.selection is null 

### ISSUE THREAD

**Issue by adampielach** [tinymce/tinymce-react#175]
I'm using **TinyMCE** with **Next.js** and when the page loads, everything is fine, editor is present, it works as intended. However, hot reloading doesn't seem to work with this package, returning me error of **Unhandled Rejection** regarding e.selection. 
I have the basic setup of the editor, nothing fancy here. I even tried removing all plugins and toolbar icons to see whether it works or not, but it doesn't.

Error appears in "@tinymce/tinymce-react": "^**3.7.0**",
Browser: Firefox **81.0**
System: MacOs **10.15.6**

<img width="857" alt="Screenshot 2020-09-29 at 08 40 11" src="https://user-images.githubusercontent.com/23332779/94528594-e8144a00-0238-11eb-8eed-8a2592685a8f.png">

**Comment by sirajalam049** [comment]
Can you show the relevant code as I couldn't replicate it, worked just fine on my machine.

**Comment by tiny-james** [comment]
It seems likely this is the same issue as https://github.com/tinymce/tinymce-react/issues/191

**Comment by DopamineDriven** [comment]
adam you could try using `await import` or even `import dynamic from 'next/dynamic';

could also wrap it in a standalone asynchronous function and pass it in to an async FC wrapper to strip the Promise from the TinyMCE components on initialization. Such as using an HTMLMouseEvent (onClick, onMouseOver, etc) so that the TinyMCE toolbar and corresponding e.selection<null>() isn't initialized until it's nonnull
 
 if all else fails I'd banish it to a serverless api function and asynchronously fetch on demand 🤷‍♂️ 
 
 hopefully that helps. about to implement it myself, I'll report my findings w/ using it in a Next/TS environment

**Comment by tiny-james** [comment]
Can you please try replicating his issue with TinyMCE 5.7? I fixed another issue that was reporting the same error message in the 5.7 release.

TinyMCE 5.7 is available on the cloud channel "5-testing" and will be on "5-stable" in two weeks.

**Comment by tiny-james** [comment]
I've had confirmation that the other issue with the same error message has been resolved by updating to TinyMCE 5.7 so please try that release (if you are using cloud the simplest method is to set the cloudChannel prop to "5-testing"). 

Unless I hear that this issue still occurs within the week I will close this case as probably fixed.

**Comment by tiny-james** [comment]
Closing as "probably fixed"
