### ISSUE TITLE
Existing content is not displayed in the HTML Editor

### ISSUE THREAD

**Issue by SuppSoftAdminZ** [tinymce/tinymce-react#180]
When pulling up existing content to render in the HTML component, it displays correctly the first time you open it. However, if you close and open the component again, the HTML component displays nothing. Even though the content is there because when I save the page, the content is saved.

The only way to make the content display is to manually refresh the browser.

Using TinyMCE: "@tinymce/tinymce-react": "^3.7.0". Tested on Chrome and Edge and issue appears on both

See attached. 
![TinyMCE Content Missing](https://user-images.githubusercontent.com/34314680/95869925-e74fdd80-0d39-11eb-8093-b5a88e32f5a4.png)

**Comment by tiny-james** [comment]
Hi,

Can you clarify what you mean by "close and open the component again"?

I suspect this problem will be due to moving the iframe that TinyMCE renders the content in. Iframes are slightly odd in that removing them from the DOM causes them to lose their content. When they refer to a URL this is not so noticeable as they will reload the content when they are re-added however when the content has been set by Javascript as it is in TinyMCE this causes the failure of the editor.

This can be worked around by hiding the editor using CSS instead of removing it from the DOM. Alternatively you can use inline mode which should be safe to move provided you keep the same elements.

Another alternative is to store the editor content before removing it and then completely destroy and recreate the editor in the new location.

**Comment by SuppSoftAdminZ** [comment]
Thank you James. 

Sorry, by 'close and open the component', I mean we are rendering this component with a DevExtreme DataGrid using PopUp mode. For example, we are using TinyMCE as an HTML editor for storing content into a database which can then be retrieved and modified. We display the content from the database in DevExtreme's DataGrid component. And to edit the content, we use DevExtreme's popup mode which opens a popup on the screen to display a form with text boxes, drop downs, and the TinyMCE component. 

When a particular record is opened, the TinyMCE correctly displays the content from the DataGrid. And the user can press Save to save changes (which it correctly saves) or Cancel. After using either Save/Cancel, if the user then tries to re-Edit that same record (or open another record to edit), the popup form displays and all the content for that record also display in the other parts of the form (like the Textboxes, Drop downs, etc.). However, the content in the TinyMCE is not displayed. It seems to be there but is just hidden. And the TinyMCE component itself acts a bit strange in that the toolbar menus display behind the popup (per another issue I submitted: https://github.com/tinymce/tinymce/issues/6100). 

I don't know if this is an issue with TinyMCE or with how DevExtreme is trying to render this component.

**Comment by SuppSoftAdminZ** [comment]
Hello James.

FYI. I figured this out. It was nothing to do with Tiny. I was rendering the component before the data had been loaded. Once I incorporated a mechanism to prevent the render until the content had been loaded, the issue no longer exists.

I'm closing this ticket
