### ISSUE TITLE
Self hosted version through npm asking for api key

### ISSUE THREAD

**Issue by aleksander351** [tinymce/tinymce-react#194]
**What is the current behavior? Describe the bug**
I installed tinymce through npm.

When I run the editor in my React component it shows a popup, this domain is not registered with Tiny Cloud.

Why should I register the free version, when it is running locally?

**What is the expected behavior?**

When I run the library on my server, there should be no api key message.

**Comment by tiny-james** [comment]
The react component will look for the tinymce global when it initializes. If it is not present then by default it will load the stable version from the cloud without an API key which leads to this message.

You have a few options. The simplest is to register a free cloud account, set the URL of your server in the account settings (I believe you can include localhost if you are testing locally) and then add the API key to the react component using the `apiKey` prop.

Alternately you can self-host tinymce on your server by just putting it and all the plugins in a folder and specifying the path to the tinymce.min.js file with the `tinymceScriptSrc` prop (or just linking to the script both have the same result). 

Finally you could try bundling tinymce into the page using webpack (or similar). Be warned though it is actually quite tricky to do that right due to the complexities of loading plugins and translations.

If you haven't read it already there is some documentation here:
https://www.tiny.cloud/docs/integrations/react/
