### ISSUE TITLE
Error with initial setup 

### ISSUE THREAD

**Issue by mikeLspohn** [tinymce/tinymce-react#2]
I have the script tag in the head and have imported and tried to use the component like so

```javascript
<Editor
        value="<p>This is the initial content of the editor</p>"
        config={{
          plugins: 'link image code',
          toolbar: 'undo redo | bold italic | alignleft aligncenter alignright | code'
        }}
        onChange={(e) => console.log('comeone')}
/>

```

This is the error I receive in the console.

```
Uncaught TypeError: Cannot read property 'length' of undefined
    at Editor.setContent (tinymce.js:40536)
    at Editor.eval (Editor.js:51)
    at Dispatcher.fire (tinymce.js:23089)
    at Editor.fire (tinymce.js:23329)
    at initEditor (tinymce.js:38400)
    at tinymce.js:38551
    at tinymce.js:8781
    at tinymce.js:8249
```

**Comment by fyrkant** [comment]
We changed the naming of some props in the latest release, so it is `init` instead of `config` (to match the `tinymce.init()` you use normally with tinymce without react) and `initialValue` instead of `value` to make it clearer that it is only the initial value and not the current value (it is not possible to use as a controlled component).

Sorry that I forgot to update the documentation page after the latest release, I have done it now to match the correct props. 🙏

**Comment by fyrkant** [comment]
It is however weird that you got an error, I would think that it would just not care about the props...

**Comment by Plash-jindal** [comment]
```
<Editor
                      inline={false}
                      init={{
                          plugins: 'link image code',
                          toolbar: 'undo redo | bold italic | alignleft aligncenter alignright | code'
                      }}
                      initialValue={this.state.mailBody}
                      onChange={this.handleChange}
                    />
```

Cant see the plugins at all. Just the textarea is visible.

**Comment by fyrkant** [comment]
This was a problem with not null checking the `initialContent` prop before setting content and has now been fixed.
