### ISSUE TITLE
highlight bad words occurrence in the editor

### ISSUE THREAD

**Issue by BasirBaidya** [tinymce/tinymce-react#209]
How can I highlight the words `onEditorChange()` event and the cursor should stay where I writing it?

**Comment by tiny-james** [comment]
Perhaps the annotation API will be helpful?
https://www.tiny.cloud/docs/advanced/annotations/

Node filters on the parser and serializer can also be helpful for this:
https://www.tiny.cloud/docs/api/tinymce.html/tinymce.html.domparser/#addnodefilter

**Comment by BasirBaidya** [comment]
Hi @tiny-james Could you please provide ***CodeSandbox*** working sample that would be very helpful.

**Comment by tiny-james** [comment]
Closing this as "out of scope".

Issues are for bug reports and feature requests. We provide low-level technical support too but we can't answer complex questions like this one. To give an indication of the scope of your question our premium spellchecker plugin has thousands of lines of code dedicated to solving a similar problem to this one. I can not release that code because it is closed source.

If you think that TinyMCE needs this feature as a general API you can make a feature request on the TinyMCE repository where product managers will review it.
