### ISSUE TITLE
Text Not Displaying

### ISSUE THREAD

**Issue by arc12420** [tinymce/tinymce-react#231]
**What is the current behavior?**

My site offers the ability to customize your screen via "Tiles". I have placed tinymce into a tile and it works great! The only issue is if we move the tile containing tinymce to the right, the text disappears from the input field and you become unable to change anything within the box. The strange part is that you can move the tile containing tinymce to the left and there are no issues. There are only issues if you move it to the right. 

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/6yz4jzrrxw?fontsize=14) or similar.**

When you click and drag a tile to the right of another tile the text within tiny mce disappears and becomes unusable.

Here is a video (Sorry in advance about the audio)
https://drive.google.com/file/d/1Im-5Yddq5sb8M1i16cyGngibaSGdjrEx/view?usp=sharing

**What is the expected behavior?**

The tile should be able to move freely and have the text still display within tiny mce and be editable.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-react`?**

Using google chrome. 
Using TinyMCE React.

**Comment by tiny-james** [comment]
This is the same issue as https://github.com/tinymce/tinymce-react/issues/170 so I'm going to close this as a duplicate. If we ever find a good solution I'll post about it in that thread.

Sadly this happens because iframes can't be moved in the dom without losing their state.

So you have 3 options:
1. use inline mode and ensure that you keep the same elements (because tinymce keeps references)
2. Don't put the editor in the page flow and use CSS to position it where you want it. This allows the iframe to stay in the DOM at the same location so it works, it's just a massive pain in website design...
3. Destroy the editor and recreate at the new location. The downside is that you lose undo history and there's the normal startup time of the editor.

Sorry we can't be more help.
