### ISSUE TITLE
"Cannot read property 'open' of undefined" in unit tests

### ISSUE THREAD

**Issue by carolbueno** [tinymce/tinymce-react#236]
I'm getting 'Cannot read property 'open' of undefined' when running my tests on chrome, using karma + enzyme. I think this is happening because the test ends before tinymce has been fully initialized. Is there a way to fix this? I tried using both options below, but the error is still occuring. 

```jsx
componentWillUnmount() {
	this.editorRef.editorManager.get(this.editorRef.id).destroy();
	this.editorRef.editorManager.remove(this.editorRef);
}
```

**Comment by tiny-james** [comment]
You are probably correct that the error occurs either because the editor has not been fully initialized or it has already been destroyed by being unmounted - which sets a whole lot of things to null to make GC work better. You shouldn't need to call destroy or remove yourself as they will be called automatically.

The best thing to do would be to wait for the editor to load before running the test. Simply wait on the onInit handler to be called before continuing (how you do that will depend on your test).

Alternatively you could consider if the test could be run without including the editor component (ie use a mock) or you could surround the editor component in an error boundary and ignore errors coming from it.

**Comment by tiny-james** [comment]
Closing as answered.
