### ISSUE TITLE
3.12 series causes text to not be editable

### ISSUE THREAD

**Issue by kanwei** [tinymce/tinymce-react#246]
**What is the current behavior?**

When you change the text, it immediately gets deleted. If you hold down a key, then some of the text manages to get through, but not with normal typing.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/6yz4jzrrxw?fontsize=14) or similar.**

Any simple onEditorChange should show this.

**What is the expected behavior?**

The editor should work as normal.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-react`?**

3.11.1 had no issues.

**Comment by tiny-james** [comment]
Hi kanwei,

The 3.12 release is designed to behave more like `<input>` and `<textarea>` in regards to how it handles the `value` prop. Specifically it treats the `value` prop as the source of truth for the editor and will rollback any value typed into the editor that is not immediately presented to the `value` prop.

I suspect the problem is that you are specifying a `value` prop but are not updating the value it presents when the editor changes. If you want the editor to not be controlled then use the `initialValue` prop to specify the starting value and leave the `value` prop `undefined`.

Here's an example of using 3.12 as an uncontrolled component:
https://codesandbox.io/s/tinymcereact-forked-nmcld?file=/src/index.js

Here's an example of using 3.12 as a controlled component:
https://codesandbox.io/s/tinymcereact-forked-bh2my?file=/src/index.js

It's certainly possible that there are bugs in this implementation so if you have found a case where this does not work then please provide a replication case by modifying this [codesandbox](https://codesandbox.io/s/6yz4jzrrxw?fontsize=14).

**Comment by kanwei** [comment]
Thanks for the reply.

We use clojurescript and re-frame (redux-like library) to handle events. We do use a controlled component - the issue is that now because of the 1ms check, it occurs faster than what our library is able to set the value. Even with the synchronous dispatch call to update the value, it's still too slow and misses about 25% of text changes. Using react hooks is probably the fastest way to update the value, so the examples are working there, but it may not work in any heavier framework.

I'm not sure the extra check is necessary since it used to work fine in the previous version.

**Comment by tiny-james** [comment]
I have slowed it down so the framework should now have 200 milliseconds to update the value. Let me know if that works.

**Comment by kanwei** [comment]
I can confirm this is now working like before. Thanks for the quick fix!

**Comment by dan-diaz** [comment]
I had v3.9.0 on my local env, and v.3.12.6 on production. I'm using this module as a controlled component within react-final-form and react-final-form-array to create a list of text editors. In production (v3.12.6) the editors were not receiving any updates. But on my local dev (v3.9.0) they were working just fine.

I'm glad I came across this github issue after so many days of trying to resolve this.

Is it possible to include some sort of warning message that indicates when the value was not accepted?
I didn't know if the root of the problem was react-final-form, or tinymce. A warning from this module would have potentially trimmed down my time to debug this. Might save time for others in the future.

As for me, I'm going to lock down my version.

**Comment by kanwei** [comment]
Yeah, I have mine locked down to 3.11.1. I still got users reporting this issue even after the increased update time - I don't think the fundamental change is good in 3.12.

**Comment by dan-diaz** [comment]
> Yeah, I have mine locked down to 3.11.1. I still got users reporting this issue even after the increased update time - I don't think the fundamental change is good in 3.12.

I tried 3.11.1 and it was flashing the content before erasing it. So I've locked it down at 3.9.0.

Thank you, btw. You saved my skin by creating this issue.
