### ISSUE TITLE
How to have separate TinyMCE instances in a React app

### ISSUE THREAD

**Issue by CZHach** [tinymce/tinymce-react#252]
**What is the current behavior? 

I realize this issue is just with my minimal understanding of TinyMCE.  But I am trying to create an example single page React app that uses TinyMCE.  This app has 3 links(routes).  I am trying to get the 3 different links to have their own instance of a TinyMCE editor. So if you edit one, it does not show up on the other 2 links

**Please provide the steps to reproduce and if possible a minimal demo of the problem via

Here is an example:
 https://codesandbox.io/s/nostalgic-nobel-b0o8n

The editor works, but the changes show across all 3 possible editors and not just the current one.

**What is the expected behavior?**
I was expecting each link to have it's own editor instance that could be edited separately from the others.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
5

**Comment by tiny-james** [comment]
So as I said on stackoverflow the main problem is that react does not know that the components are different so it reuses the same component. This is easily fixed by [giving the components a `key` prop](https://reactjs.org/docs/lists-and-keys.html).

Once you've done that it comes down to state management. You can't have the state inside the components (or if you do you need to fetch their data from a server when they mount) because they'll be unmounted by react-router-dom when you switch pages so you have to extract the state to a higher component. 
https://codesandbox.io/s/festive-galois-etkyr?file=/src/App.js

Note that this keeps the content of the editors when you switch between them but they are effectively new editors each time so the undo history is lost. The only way around that is to hide and show the editors using pure css and not ever remove them from the dom.

**Comment by CZHach** [comment]
Thank you! I am not sure how to close issues on here but I believe this can be closed or moved if needed?  Thanks again!

**Comment by tiny-james** [comment]
Ok, closed!
