### ISSUE TITLE
Inline editor not working in TinyMCE 5.9.0 onwards

### ISSUE THREAD

**Issue by robfenlon** [tinymce/tinymce-react#283]
**What is the current behavior?**
Rendering the editor in inline mode with default options fails:

![image](https://user-images.githubusercontent.com/16761849/132197617-4bd20fe2-20c2-4d46-8943-b8717109ef49.png)

**Demo available here:**
https://codesandbox.io/s/tinymce-react-inline-demo-zc99h
The tinymce dependency is set to 5.9.0 to repro the bug, change the dependency version to 5.8.2 and it will work again.

This seems to have been introduced during the fix for TINY-3254, as part of [PR 6892](https://github.com/tinymce/tinymce/pull/6892/files#diff-beb854036bfd4f58e481442b9fdbffa580e2075fed56793c3ab84a14397e0210). The function logic has changed to look at the `no_events` flag in the args. This results in `updatedArgs.content` being undefined.

In the Editor component, during the `PostRender` event, what is the desired effect of the `no_events` flag in the args object? https://github.com/tinymce/tinymce-react/blob/0a3a782cd6b2a1405c19ebf5b0e4b5db1164e557/src/main/ts/components/Editor.tsx#L331

**Comment by tiny-james** [comment]
Thanks for the amazing bug report. I showed it to the editor team and they were quite impressed you identified the root cause!

Since this is fairly serious it will likely be patched in TinyMCE before the release of 5.9 on stable. I'll update here when it has been patched.

Also in case you're interested drop your [CV here](https://www.tiny.cloud/about/#careers) as Tiny hires globally.

**Comment by tiny-james** [comment]
Ref: TINY-7956

**Comment by tiny-james** [comment]
The 5.9.2 release is now available on NPM which should fix this issue.
