### ISSUE TITLE
Controller component TinyMCE with Formik is taking more than 200 milliseconds so changes are rolled back and causes a loop

### ISSUE THREAD

**Issue by davidbejarcaceres** [tinymce/tinymce-react#285]
**What is the current behavior?**
I´m currently working with Formik, and one of the custom inputs is the TinyMCE editor, and because my Formik implementation is very packed with other custom inputs and constantly making back-end calls, after every onEditorChange() all the form is updated, so after a few letters written in the editor, the re-render of the Formik starts to have a loop and rolled back the previous letter written, the value and the current content of the editor do not match.

I checked the documentation the [controlled component](https://www.tiny.cloud/docs/integrations/react/#usingthetinymcereactcomponentasacontrolledcomponent), and I´m aware about the 200 milliseconds before rollback, wich is probably why I´m having this infinite loop. Unfortunately I´m not capable optimizing too much my Formik implementation to reduce the rendering time on each change.

**Please provide the steps to reproduce**
1. Add a formik with a re-render time above 200 milliseconds (like 400ms).
2. Add TinyMCE as a custom input and like a (https://www.tiny.cloud/docs/integrations/react/#usingthetinymcereactcomponentasacontrolledcomponent).
3. Write text at a fast pace.
4. The "rolle back last character" loop appears.

**My current implementation**
![image](https://user-images.githubusercontent.com/17320214/133967641-3ef10383-4099-41d4-8075-d32205cdeab5.png)

**What is the expected behavior?**
A way to avoid this infinite "roll back last letter" loop, maybe a prop to the component to change the 200 milliseconds and use a custom value?.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-react`?**
"@tinymce/tinymce-react": "^3.12.6",
"react": "^16.10.1"

**Comment by tiny-james** [comment]
This setting is a trade off. I think I will have to make it configurable as it's already set quite high for a simple use case and it effects usability the higher I set it.

**Comment by tiny-james** [comment]
See https://github.com/tinymce/tinymce-react/pull/290

**Comment by tiny-james** [comment]
The `rollback` setting is now available on 3.13.0. Set it to a number to set the rollback timer to that number or set it to `false` to disable rollback.

Note that I suspect you will still have problems because of the incredibly slow update of value. When value is set it triggers the editor to change to match that value if it does not already. So if the time between someone typing something and the value being updated is large you will lose typed content simply because they have typed more since.

With TinyMCE controlled components are normally the wrong way to go. Instead you could simply save the content on a timer or on page navigation like here:
https://github.com/tinymce/teach-rtc/blob/main/client/src/api/api.js#L359-L411
