### ISSUE TITLE
Editor gets immediately dirty without any user interaction

### ISSUE THREAD

**Issue by Mario-Eis** [tinymce/tinymce-react#298]
**What is the current behavior?**

Editor is in controlled mode. After setting a value, the onEditorChange event is immediately called, adding some lindebreaks and whitespaces to the markup. This results in the editor and forms getting dirty immediately and without any user input. It would not be a problem to add whitespaces and linebreaks to the markup AFTER any user interaction. But in the current form its a pain to handle. The only possible solution I came up with included a second Editor and compare their values to find out if the markup was manipulated by a user or by the editor itself. But to be honest, that solution is anything but clean.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/6yz4jzrrxw?fontsize=14) or similar.**

https://codesandbox.io/s/tinymce-react-forked-iygl6

**What is the expected behavior?**

Only changes made by users should result in an onEditorChange event .

**Comment by Mario-Eis** [comment]
Update: There was something wrong with the sandbox example. I updated it.

**Comment by tiny-james** [comment]
Here's how you are meant to do this with 3.11 and up:
https://codesandbox.io/s/tinymce-react-editor-dirty-p9g70?file=/src/index.js

Basically you can use the `initialValue` prop to set the starting content of the editor (even asynchronously) which will reset the dirty state.

The `onEditorChange` handler has to be called any time the editor value differs from the prop passed for `value`. It must do this because the editor value will be (after a brief time) updated to match the `value` prop.

The reason for the change was that previously it was very tricky to set the initial value of the editor asynchronously.

**Comment by Mario-Eis** [comment]
@tiny-james Does that mean, its now needed to click two save buttons? One to commit the changes in the tinymce control to the upper form (otherwise the form would not get into its dirty state). And another one to save the form?
I think that would prevent us from updating to >=3.11 forever.

**Comment by Mario-Eis** [comment]
@tiny-james how is this supposed to work controlled?

**Comment by Mario-Eis** [comment]
I put together a new Sandbox https://codesandbox.io/s/tinymce-react-editor-dirty-forked-4uk9n?file=/src/index.js
This one simulates an upper form handler.

**Comment by Mario-Eis** [comment]
I updated the sandbox to tinymce-react 4.0.0 and react 18. The issue is still present :(

https://codesandbox.io/s/tinymce-react-editor-dirty-forked-4uk9n?file=/src/index.js

**Comment by haresh6x** [comment]
Any update? I am facing the same issue. Tried older versions but it gets immediately dirty.

**Comment by tiny-james** [comment]
The problem here is that the editor will normalize the content (add spaces, fix missing tags, ect..) so your system needs to take the normalized content as the starting point. It's fine if you don't want to save that to the server as it should be semantically identical. 

Here's a demo:
https://codesandbox.io/s/tinymce-react-editor-controlled-dirty-with-normalisation-x517fd

**Comment by Mario-Eis** [comment]
> The problem here is that the editor will normalize the content (add spaces, fix missing tags, ect..) so your system needs to take the normalized content as the starting point. It's fine if you don't want to save that to the server as it should be semantically identical.
> 
> Here's a demo: https://codesandbox.io/s/tinymce-react-editor-controlled-dirty-with-normalisation-x517fd

But the content is from multiple sources. Is there a way to normalize the content that is already in the database? On the backend side?
Is it guaranteed, that the normalization will never ever change with future updates? If that happens, the whole database would be dirty again.
Where is the normalization documented?
Can the normalization be turned off?

**Comment by Bulala-liu** [comment]
why is it closed? 
Is it a way to distinguish which triggers the onEditorChange between onInit and user input? So i can control the dirty state of the upper form in a controlled mode

**Comment by tiny-james** [comment]
> why is it closed?
Because the question was answered. There is nothing I can change in the integration to "fix" this problem. You simply have to use the tools that the integration provides to solve it.

> Is it a way to distinguish which triggers the onEditorChange between onInit and user input?
Simply query the editor state `onInit` as in the example I gave above. The editor will normalise the input given before the `onInit` happens so you have access to the normalised version which you can use as the unchanged reference to detect changes caused by user input.

**Comment by Bulala-liu** [comment]
> > why is it closed?
> 
> Because the question was answered. There is nothing I can change in the integration to "fix" this problem. You simply have to use the tools that the integration provides to solve it.
> 
> > Is it a way to distinguish which triggers the onEditorChange between onInit and user input?
> 
> Simply query the editor state `onInit` as in the example I gave above. The editor will normalise the input given before the `onInit` happens so you have access to the normalised version which you can use as the unchanged reference to detect changes caused by user input.

I figure it out immediately. Thank you for your reply.
