### ISSUE TITLE
Error and textaera disabled when using ReactPortal

### ISSUE THREAD

**Issue by IamFonky** [tinymce/tinymce-react#301]
**What is the current behavior?**
I'm using ReactPortal to allow displaying multiple view while avoiding loosing react state.
It seem to me that every time the dom changes, tinyMCE is autodestroying itself but I can't prevent it from doing that.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/6yz4jzrrxw?fontsize=14) or similar.**
[Look at this codesandbox example plz](https://codesandbox.io/s/tinymcebug-pkf2q?file=/src/App.tsx)

**What is the expected behavior?**
I expect the editor to keep working

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-react`?**

tinymce : cloud version (5.10.2 ?)
react-tinymce : 3.13.0
browsers : Firefox, Chromium, Edge.

Was not bugging with tinyMCE 4 self-hosted

**Comment by IamFonky** [comment]
https://github.com/tinymce/tinymce-vue/issues/10

Might be related

**Comment by tiny-james** [comment]
## The problem with Portals

I'm not certain the mechanism that Portals use but given your description and demo I think it's highly likely that TinyMCE is getting removed from the DOM and reinserted elsewhere.

With any element but an iframe this is completely fine, however an iframe loses all state (ie the contained document) when it is removed from the DOM.

TinyMCE uses an iframe to separate the content from the rest of the page and to maintain a separate selection range. In modern browsers (not Internet Explorer) we could use a shadow-dom to separate the styling but that can't yet give us a separate selection range, only an iframe can do that. In the current version of TinyMCE the iframe is treated as the source of truth for the editor's value so once it is removed the editor content can not be retrieved.

## TinyMCE's potential future

The editor team is aware of this problem and they are currently updating the editor to a model based system which allows other features like real-time collaboration. In the model based editor as the iframe is not the source of truth it should be possible to make it re-initialize after being moved.

## Workarounds
So what are your options? Well they are currently...

### Option 1: use inline mode
https://codesandbox.io/s/tinymcebug-inline-works-with-portals-v5zvy

Inline mode has downsides:
- the toolbar is only shown when the content has focus
- the selection can not be remember when the editor loses focus

As long as all you do is move the nodes around then inline mode will work fine. If you try cloning nodes it will break because the editor keeps references to the nodes.

### Option 2: Track the editor content and force a re-init of the editor

The idea works like this:
1. Store the content and current selection of the editor
2. Destroy the editor at the old location
3. Create a new editor with the `initialValue` set to the stored content
4. When the editor re-inits then set the selection to the stored one.

Re-initing a standard iframe editor tends to look better then the inline mode however you will lose the undo history.

Note that while it isn't always needed I recommend specifying the `key` for the react component and ensuring that it changes when you intend to force the re-init as this will ensure that react doesn't just try to move the existing component.

## Summary

I'm closing this issue because it is currently unfixable in the react integration. 

I will continue to request the editor team for the changes we need in TinyMCE to resolve this and related editor movement problems.
