### ISSUE TITLE
Assign command to a html element inside a tinymce redactor

### ISSUE THREAD

**Issue by KirillPenkin** [tinymce/tinymce-react#315]
In order to provide requested functionality I need html controls (```input``` and ```dropdown```) inside a tinymce content.
I found the way to display them. Redactor just displays the given ```html```.

I need to execute some code on inner input or dropdown change.
The problem is that tinymce is rendering in an ```iframe```, so I can't access a DOM and ```addEventListener```.

How should I approach this? It there a built-in solution?

**Comment by tiny-james** [comment]
If the events bubble then you can simply register them on the editor with `editor.on('event', (evt) => { /* do stuff */ })`. Unfortunately this is unlikely to be helpful for form elements because they have various browser quirks - for example a checkbox won't bubble up a click event on Firefox (it also won't toggle). 

In the case of the change event bubbling isn't going to help because the editor has its own change event. For that you'll have to find the form elements using `querySelectorAll` on the body (`editor.getBody()`) and then add event listeners. You can do this on the `onSetContent` event. If the content is going to be overridden I'd also add a handler for `onBeforeSetContent` to remove the listeners.

Here's a basic example:
https://codesandbox.io/s/mystifying-hooks-6un2ee?file=/src/index.js

Note this is probably still not going to work very well, but good luck.
