### ISSUE TITLE
how to hide the upload tab in image upload modal

### ISSUE THREAD

**Issue by topskishan** [tinymce/tinymce-react#324]
i want to hide the upload tab from image upload dialog modal because its effecting the general tabs on save not able to call te

		<Editor
			initialValue=""
			value={value}
			onEditorChange={handleUpdate}
			onBeforeAddUndo={handleBeforeAddUndo}
			init={{
				menubar: false,
				selector: "textarea#file-picker",
				file_browser_callback_types: "image",
				images_dataimg_filter: function (img) {
				return !img.hasAttribute("internal-blob"); // blocks the upload of <img> elements with the attribute "internal-blob".
				},
				images_upload_handler: function (blobInfo, success, failure) {
				console.log("images_upload_handler");
				const body = {
					devOrderId,
					summernoteImage:
					"data:" + blobInfo.blob().type + ";base64," + blobInfo.base64(),
				};
				uploadImage(body);
				success("data:" + blobInfo.blob().type + ";base64," + blobInfo.base64());
				},
				file_picker_callback: filePickerCallback,
				automatic_uploads: true,
				pagebreak_separator: `<div class="page-break" style="page-break-after:always;"><span style="display:none;">&nbsp;</span></div><p>&nbsp;</p>`,
				forced_root_block: "",
				plugins: [
				"imagetools lists link image paste wordcount pagebreak image code fullscreen",
				],
				draggable_modal: true,
				toolbar:
				"fullscreen | code image pagebreak undo redo | formatselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent",
			}}
		/>;

i need to call the images_upload_handler on save button of modal to handle another function and api calls

**Comment by tiny-james** [comment]
To hide the image upload tab set `image_uploadtab` to false.
https://www.tiny.cloud/docs/tinymce/6/image/#image_uploadtab

For example:
https://codesandbox.io/s/new-brook-c8eg96?file=/src/index.js

Note that one of the things that changed with TinyMCE 6 was that the image_upload_handler should now return a promise instead of using callbacks.
https://www.tiny.cloud/docs/tinymce/6/file-image-upload/#images_upload_handler

A number of other things changed between 5 and 6, for example `file_browser_callback_types` and `forced_root_block` were removed and the `plugins` can't be an array of space separated strings - it must either be an array or a space separated string, not both.
https://www.tiny.cloud/docs/tinymce/6/migration-from-5x/

Also note that the `selector` or `target` setting is not used for the react integration and it will be ignored.
