### ISSUE TITLE
fontsizeselect doesn't show up

### ISSUE THREAD

**Issue by ouroboroscoding** [tinymce/tinymce-react#337]
**What is the current behavior?**

Same as title, fontsizeselect simply will not show up in the toolbar. Nor does fontselect or formatselect now that I check.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io]**

https://codesandbox.io/s/little-river-76rcdw?file=/src/index.js

**What is the expected behavior?**

That it shows up.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-react`?**

6 in chrome and I assume any other browser

**Comment by tiny-james** [comment]
With version `4.0` of the integration the default cloudChannel became `6`. This was a breaking change because TinyMCE 6 needs an updated configuration.

I recommend checking out the migration guide:
https://www.tiny.cloud/docs/tinymce/6/migration-from-5x/

The names of these three toolbar items you mention were changed in TinyMCE 6. In fact quite a lot of things were renamed:
https://www.tiny.cloud/docs/tinymce/6/migration-from-5x/#things-we-renamed

- `fontsizeselect` became `fontsize`
- `fontselect` became `fontfamily`
- `formatselect` became `blocks`

**Comment by tiny-james** [comment]
Note that if you wish you may continue to use TinyMCE 5 by setting the `cloudChannel` prop to `5`.

**Comment by ouroboroscoding** [comment]
I have never used TinyMCE before in my life, so I don't know what I'd be migrating too. I got the information from this page

https://www.tiny.cloud/docs/advanced/available-toolbar-buttons/

However, now that I looked it up again expressely for this comment, I see that it says v5 in the top left. It's pretty bad that by default it doesn't take you to the latest version when you go to the page, I mean it's not like the version is in the url. I know that has nothing to do with the react module specifically, but man, what a bad experience trying to make sense of this for a new user. I kept going in circles and nothing anywhere says "hey, this functionality we took you do directly, is old and not available anymore"

**Comment by tiny-james** [comment]
Thanks for the feedback. I'll bring it up with the docs team.

**Comment by tiny-james** [comment]
Can I ask how you ended up on the 5.x docs? Did you use google or follow a link somewhere?

The docs links are unfortunately confusing because the version was not included in the URL of the 5.x docs when it was first created 3 years ago. We can't change it because it would break a lot of version specific things (such as stackoverflow posts) however we do plan to redirect it to a URL specifically containing the version once we have completed the 6.0 docs (I am told that could take up to 2 months). I have suggested that we also include a banner on the 5.x docs that indicate they are for an older version with a link to the equivalent page on the 6.0 docs.

**Comment by tiny-james** [comment]
It looks like I missed updating the links in the tinymce-react README.md. They will be [updated in a PR](https://github.com/tinymce/tinymce-react/pull/338) soon.

**Comment by ouroboroscoding** [comment]
> Can I ask how you ended up on the 5.x docs? Did you use google or follow a link somewhere?

A believe a combination of the links in the react readme and googling toolbar options, though I honestly can't remember 100% percent because I spent a few hours first googling if there was was some reason it didn't work, which obviously gave no results, and then trying different ways to add it to my project, cloud vs downloading the files to my public folder vs trying to import from installed npm module, anything to understand why those items wouldn't show up in the toolbar. Of course now I understand why, but until you pointed out the version thing I was at a loss and couldn't think of anything to do but make this issue.

I feel kind of foolish to be honest, I made a point to look at the url to make sure it didn't show a version in it, but I completely blanked out on noticing it on the page itself, I made a dumb assumption it would take me to the latest by default.

**Comment by tiny-james** [comment]
> I feel kind of foolish to be honest

Don't be! You're just the one willing to speak up. I'm sure there are many people out there that got confused and just worried it was them, instead now the docs team can actually fix the problem because someone pointed it out to us. Thanks for your help!
