### ISSUE TITLE
Unable to hide menu

### ISSUE THREAD

**Issue by peterbooy** [tinymce/tinymce-react#356]
I did this in the component, but couldn't hide the menu

![image](https://user-images.githubusercontent.com/44921591/177502669-e693ba1f-3d17-48d4-9f13-6fc05baf58de.png)

![image](https://user-images.githubusercontent.com/44921591/177502706-4a2c9242-448a-4150-96cb-3095babee2f7.png)

**Comment by tiny-james** [comment]
Yep, xr0master is right. The prop `menubar` does not exist and you should use the `init` prop to specify it.

You can read about the available settings here:
https://www.tiny.cloud/docs/tinymce/6/react-ref/

The `toolbar`, `plugins` and `inline` props are all confusing because they duplicate the settings in `init` but they've been around since the first version of this integration so sadly removing them (even in a major version bump) would break too many people's apps.
