### ISSUE TITLE
Plugins missing on 4.1.0

### ISSUE THREAD

**Issue by rafavalerio** [tinymce/tinymce-react#370]
**What is the current behavior?**
Seems like a few plugins are missing on v4.1.0?

I am getting the following 404s (`print` and `paste`):
- `https://cdn.tiny.cloud/1/r0fnanx38xzjqiced4u6hu5v8t2cyyaktjluyuon3yarx4hw/tinymce/6.1.2-8/plugins/print/plugin.min.js`
- `https://cdn.tiny.cloud/1/r0fnanx38xzjqiced4u6hu5v8t2cyyaktjluyuon3yarx4hw/tinymce/6.1.2-8/plugins/paste/plugin.min.js`

Also, it seems the toolbar selector `formatselect` doesn't add the select on the toolbar. It seems it changed to `styles` now.
Is there a place to easily get a diff between versions and know what to update?

Cheers,

**Comment by tiny-james** [comment]
The tinymce-react integration can work with both TinyMCE 5 and 6 but if you don't specify which you want it will default to 6 as of the 4.x release. Both the `print` and `paste` plugins were made a core part of TinyMCE in 6 which is why they don't exist as plugins any more.

To specify that you want to keep using version 5 (and avoid other config changes) you can set the `cloudChannel` to '5':
https://codesandbox.io/s/cloudchannel-set-to-5-gnh2yp

Otherwise to migrate to TinyMCE 6 you will need to change your configuration as in TinyMCE's migration guide:
https://www.tiny.cloud/docs/tinymce/6/migration-from-5x/

**Comment by rafavalerio** [comment]
Thanks for the quick reply! 🙏
