### ISSUE TITLE
Could not use numlist bullist charmap emoticons in toolbar

### ISSUE THREAD

**Issue by X0rD3v1L** [tinymce/tinymce-react#382]
I am not able to get the numlist bullist charmap emoticons options in the menu bar even though I included in the toolbar part of the code.

```
<Editor
         onInit={(evt, editor) => editorRef.current = editor}
         init={{
           height: 412,
           width: 780,
		   forced_root_block: 'div',
           menubar: false,
		   statusbar: false,
		   inline: false,
           plugins: [
             'advlist autolink lists link image charmap print preview anchor',
             'searchreplace visualblocks code fullscreen',
             'insertdatetime media table paste code help wordcount'
           ],
           toolbar1:
           'bold italic underline alignleft aligncenter alignright | outdent indent | numlist bullist | removeformat undo redo | forecolor backcolor | charmap emoticons | pagebreak | charmap',
           toolbar2:
           'fontfamily fontsize',
           content_style: 'body { font-family:Helvetica,Arial,sans-serif; font-size:14px }'
         }}
       />
```
@tinymce/tinymce-react@4.2.0
node v16.13.1
react: "^18.1.0"

![editorView](https://user-images.githubusercontent.com/46685302/187356949-fca18ddb-8773-4dd8-b6bd-f8dd1b808613.png)

**Comment by tiny-james** [comment]
I suspect the plugins are not loading because they are specified using the old format that is not supported in TinyMCE 6.
See this: https://www.tiny.cloud/docs/tinymce/6/migration-from-5x/#plugins

If you wish to keep using TinyMCE 5 you can specify the [cloudChannel](https://www.tiny.cloud/docs/tinymce/6/react-ref/#cloudchannel) prop and set it to 5.
