### ISSUE TITLE
Hosting the TinyMCE package with the React framework not working in production

### ISSUE THREAD

**Issue by sgidd** [tinymce/tinymce-react#387]
I have implemented tinymce using package manager with hosting which works fine in my localhost but when it is deployed in production build AWS its failing with below error :

![image](https://user-images.githubusercontent.com/47084698/193650192-008ea354-7999-4030-b08a-644c2427de7d.png)

I have followed the step as suggested in https://www.tiny.cloud/docs/tinymce/6/react-pm-host/ 

![image](https://user-images.githubusercontent.com/47084698/193650475-51acf265-9a00-43ce-a5ac-874d60bf18a8.png)

![image](https://user-images.githubusercontent.com/47084698/193650660-c63125ef-fe05-46d0-a9ff-b2fe3672f2ec.png)

**package.json file :** 

"scripts": {
     "prebuild": "npm run tinymce-postinstall",
    "build": "webpack --mode production --env BASE_URL=/api",
    "predev": "npm run tinymce-postinstall",
    "dev": "npm run webpack-dev",
}

any assist on this will be great help .

**Comment by tiny-james** [comment]
According to the error message the file is being served as HTML instead of Javascript. I  think you have some settings wrong on AWS.

This stackoverflow question seems related to your problem so maybe try one of those solutions:
https://stackoverflow.com/questions/67925203/aws-cloudfront-serving-javascript-modules-as-wrong-mime-type-text-plain
