### ISSUE TITLE
External Pluginza plugins are literally impossible to integrate.

### ISSUE THREAD

**Issue by TimMTech** [tinymce/tinymce-react#413]
**What is the current behavior?
The different pluginza plugins are not working in react Editor component.

**What is the expected behavior?**
Plugins need to be shown.  Instead, only gives me error

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-react`?** React version 18/ Tinymce 6

**Comment by tiny-james** [comment]
The normal reason for these errors is that the plugin is not in a location that the editor can find at runtime (for example if you leave it in the `node_modules` instead of hosting it). 

I attempted to replicate your reported problem using the N1ED plugin from pluginza and it works as far as I can tell.
https://codesandbox.io/s/pluginza-n1ed-2k19q2

To implement it I first put the plugin in the `public` folder:
![image](https://user-images.githubusercontent.com/41130888/210714797-fb8c8ebd-0456-4230-aec9-2e7669b4131b.png)

Then I referenced it as an external plugin:
```
      init={{
        external_plugins: {
          N1ED: "/plugins/N1ED/plugin.min.js"
        },
        plugins: ["N1ED"]
      }}
```

Does this solve your issue? If not then please provide more details like your editor configuration and how you are hosting the plugin.
