### ISSUE TITLE
cursor to the first position when use onEditorChange function

### ISSUE THREAD

**Issue by yuer0608** [tinymce/tinymce-react#444]
My code is similar that

```
function MyComponent({initialValue}) {
  const [value, setValue] = useState(initialValue ?? '');
  useEffect(() => setValue(initialValue ?? ''), [initialValue]);
  return (
    <Editor
      initialValue={initialValue}
      value={value}
      onEditorChange={(newValue, editor) => setValue(newValue)}
    />
  );
}
```

everytime, the cursor will to the first position when I edit content after.
how I do ?

**Comment by lorenzo-pomili** [comment]
I cannot replicate it, can you provide use an example and the step by step instructions to replicate it?

also version of the editor and the browser are you using, could be a very useful information

**Comment by duongnq2798** [comment]
This problem is likely due to the way the component updates its internal state.

**Comment by danoaky-tiny** [comment]
I agree with @duongnq2798, closing.

**Comment by hubertlepicki** [comment]
I think this is indeed related to state management of the parent component *but* the thing that may be confusing is the naming of properties for the Editor, or how it works.

I found that changing initialValue={initialValue}, i.e. changing the variable intialValue results in precisely the above behavior, i.e. the cursor jumps to the beginning of the editor.

In my case the fix was not to update the initialValue

**Comment by danoaky-tiny** [comment]
@hubertlepicki Correct, you can see https://www.tiny.cloud/docs/tinymce/6/react-ref/#initialvalue for more info.
