### ISSUE TITLE
onEditorChange is fired three times if text was selected and is overwritten by paste

### ISSUE THREAD

**Issue by m4r71n** [tinymce/tinymce-react#470]
**What is the current behavior?**

`onEditorChange` is fired three times if text was selected and is overwritten by paste. Also the content is wrong.
Reproducible on https://tinymce.github.io/tinymce-react/iframe.html?id=editor--controlled-input&viewMode=story with Firefox 117, Edge and Chrome 116.

Select some text and paste other text with `ctrl+v`. Please see attached video: [onEditorChange.webm](https://github.com/tinymce/tinymce-react/assets/6043876/d69e25c8-b17b-46f0-830e-c7fa3f5c23db)
The logpoint in the video is on:
```
onEditorChange: function onEditorChange(e) {
    return setData(e)
}
```

**What is the expected behavior?**

The correct content with the pasted text.

**Comment by danoaky-tiny** [comment]
I've been able to replicate your case with 2 identical logs after pasting over some content, see here: https://codesandbox.io/p/sandbox/runtime-water-gff5js

This is because `onEditorChange` is called for several different TinyMCE events, so it's possible for some events to fire at the same time **and** with the same content.

As a workaround, you could try and debounce calls made to your `onEditorChange` callback.

Let us know if that helps.
