### ISSUE TITLE
Using with TinyMCE 5 Without Cloud

### ISSUE THREAD

**Issue by dkrefta** [tinymce/tinymce-react#60]
Hello guys, I was wondering if is someone here using the new TinyMCE without Cloud and if that worth to upgrade to the new because I will not use the Cloud from TinyMCE and I saw a lot of things that are different from the older version. 
How you guys are using with React? Besides of that I saw this one #57 but I don't think is the best solution.

**Comment by brymon68** [comment]
I can say that I tried creating a POC of TinyMCE5, hosting the tinymce.min.js file myself and I keep hitting receiving: 

```
This domain is not registered with TinyMCE Cloud. Start a free trial to discover our premium cloud services and pro support.
```

I think the documentation is lacking in this regard. They say to host your own and everything works but it doesnt. 

See: https://codesandbox.io/s/rwn4wzqrkp

**Comment by androb** [comment]
It isn't by design. You are supposed to be able to host your own tinymce.min.js, plugins etc. without receiving this error. Will try and get someone to look at this.

**Comment by brymon68** [comment]
Thanks @androb . I should also mention that in my testing, when trying to host the tinymce.min.js file there are other dependency import errors such as: 

 https://myhost/theme.min.js net::ERR_ABORTED 404 (Not Found)

Not sure if there is a way to import the entire codebase or not

**Comment by dkrefta** [comment]
@brymon68 sure, I did the same thing (host on my own ) but without lucky too, maybe there is, in fact, some issues to use without Cloud and logged.
Thanks @androb 🥇

**Comment by EkimChau** [comment]
Hi @brymon68, I had a look at your fiddle and it appears the version you used loads Tinymce 4.
The latest Tinymce React wrapper is Version 3+, which should load Tinymce 5, see https://github.com/tinymce/tinymce-react.

The react wrappers work by fetching the tinymce.min.js from our cloud distribution which requires an api key, otherwise you get the nag message.  The react wrapper accepts an api_key property, when set should remove the nag message.

@brymon68 re: https://myhost/theme.min.js net::ERR_ABORTED 404 (Not Found)
This could either be a config error where the theme URL is configured to the wrong location, or the theme.min.js file is missing on your webserver.  Try downloading our self hosted package and maintain the file structure see below.

@dkrefta To use Tinymce without the cloud, you will need to host the tinymce.min.js core file on your own web server, the latest core can be downloaded here https://www.tiny.cloud/get-tiny/self-hosted/
This should never display a nag message.

**Comment by brymon68** [comment]
@EkimChau  - Thank you. The key fix for me to was to download source from https://www.tiny.cloud/get-tiny/self-hosted/. I wasn't aware the source was available there. Not receiving API warning any longer!

**Comment by dkrefta** [comment]
@EkimChau probably that will resolve my problems here, thanks a lot for the tip.

**Comment by sshaw** [comment]
Also see [Usage with module loaders](https://www.tiny.cloud/docs/advanced/usage-with-module-loaders/) in the docs.

**Comment by liuxuelian09** [comment]
> 
` <script src='https://xxx.com/tinymce/tinymce5.min.js'></script>` import TinyMce in React,I still get the nag message. 

The nag message is 'We’re unable to check your domain because the referer header is missing. Please read the Guide  on how to ensure your referer header is present, so we can then customize your editor experience.'

Can you help me see how to solve it?
