### ISSUE TITLE
How to test with React? createTextRange error

### ISSUE THREAD

**Issue by vctormb** [tinymce/tinymce-react#61]
I'm trying to test the editor with Jest and React Testing Library, which uses jsdom.

When I run my test I receive the following error:
`TypeError: doc.body.createTextRange is not a function`

![image](https://user-images.githubusercontent.com/13953703/55496185-d1c20980-5614-11e9-95c3-26ad7a124ba3.png)

How can I fix it?

Also, is it possible to mock the skin and content css paths, because in the test I'm receiving the following error:
`Error: Could not load link: "http://localhost/assets/skins/content/default/content.min.css"`

![image](https://user-images.githubusercontent.com/13953703/55496340-34b3a080-5615-11e9-8a19-ce3ded62beed.png)

**Comment by dkrefta** [comment]
You can use [](https://www.cypress.io/) :D

**Comment by SimonFc** [comment]
I think the createTextRange it's failing on is from [here](https://github.com/tinymce/tinymce/blob/master/src/core/main/ts/api/dom/Selection.ts#L340). It seems like jsdom simply haven't implemented any of the methods. Looks like it's an open [request](https://github.com/jsdom/jsdom/issues/317) though. Jsdom isn't anything that's officially supported by TinyMCE so I would expect that you would encounter more issues even if you would get past that one.

You can set the [base_url](https://www.tiny.cloud/docs/configure/url-handling/#document_base_url) in Tiny so this might be of help with your second issue. The issue is one related to your setup though and isn't anything I can say anything for certain about.

**Comment by vedran-passendo** [comment]
It is a shame that a product you are paying for (not a small amount) can not provide any way to be tested in React which is a requirement for any serious development team. Being forced to exclude tinyMCE components from test coverage is one way to solve it but I don't see why investing a couple of developer hours to make the library testable, to at least be able to input text and see if callbacks are executed, is a big deal for a company developing tinyMCE.

**Comment by nitinja** [comment]
Agreed, had to exclude component that uses this lib from testing because of this issue.
