### ISSUE TITLE
Menu initial option not working

### ISSUE THREAD

**Issue by danlupascu** [tinymce/tinymce-react#64]
"menu" initial option is not working.

Here's a sandbox: https://codesandbox.io/s/980z17761y?fontsize=14 .

As you can see, the initial options are:
```
const initOptions = {
    menu: {
      edit: {
        title: "Edit",
        items: "undo redo | cut copy paste pastetext | selectall"
      },
      insert: { title: "Insert", items: "link media | template hr" },
      view: { title: "View", items: "visualaid" },
      format: {
        title: "Format",
        items:
          "bold italic underline strikethrough superscript subscript | formats | removeformat"
      },
      table: {
        title: "Table",
        items: "inserttable tableprops deletetable | cell row column"
      },
      tools: { title: "Tools", items: "spellchecker code" }
    },
    branding: false
  };
```

So, according to the configuration, the menu should have the following items: `edit, insert, view, format, table, tools`, but instead, it has `file, edit, view, format`.

No matter how I change the `menu` option, it is not working. The `menubar` option is working though.

**Comment by SimonFc** [comment]
Hi,
In order to specify what menus to show and in what order you need to use the [menubar](https://www.tiny.cloud/docs/configure/editor-appearance/#menubar) option. (An object can never guarantee the order of its properties which is why it would never work with simply the `menu` option).

Also, make sure that all the plugins you're using in the items list are added as well!

**Comment by danlupascu** [comment]
I don't see a reason for closing this because it's obvious that it's not working as expected. Am I missing something?

Can you take a look at the sandbox again, please? (https://codesandbox.io/s/980z17761y?fontsize=14).

I've updated the `menu` option and now it's as simple as
```
const initOptions = {
    menu: {
      edit: {
        title: "Edit",
        items: "undo redo"
      }
    },
    branding: false
  };
```

As you can see, there are no plugins. So, we should have just a menu item, that is `Edit`, with just two options: `undo` and `redo`, but as you can see, it's not working.

**Comment by SimonFc** [comment]
I compared it with the behavior of Tiny4 and it's different so it's most likely a regression. My bad for disregarding it at first! A lot of things concerning the UI changed with the recent Tiny5 release.

This is an issue with [Tiny](https://github.com/tinymce/tinymce/issues) though and not the tinymce-react wrapper. I've created an internal ticket and added it to out tracking system so it shouldn't be too long until we would be able to take a look at it.

Thanks for reporting it!

**Comment by danlupascu** [comment]
Okay, I thought the issue is with the react wrapper because it was so well documented in the main library and I thought that it was tested and it's working there.

Thank you for taking action!

**Comment by ansal-exp** [comment]
Any update on this??

**Comment by tiny-james** [comment]
The internal ticket TINY-3580 has not been scheduled and no decision has been made on if the change in behavior is intended - if it is intended the docs should be updated as they currently imply only `menu` is needed. I will make some inquiries.

The workaround is to simply specify the `menubar` setting as well as the `menu` setting:
https://codesandbox.io/s/tinymce-react-menu-and-menubar-o1rcx

Also worth noting that this issue can not be fixed in the tinymce-react repository as it is a tinymce feature.

**Comment by tiny-james** [comment]
After a internal discussion we will be updating the docs ( DOC-757 ) to correctly document the TinyMCE 5 behavior as it is intended.
