### ISSUE TITLE
On Blur problem with React Hook API

### ISSUE THREAD

**Issue by Aldorus** [tinymce/tinymce-react#65]
Hello everybody, nice work on this package. 

I'm trying to update one of my project to use the new hooks system and I end up having a strange behavior 

https://codesandbox.io/embed/5k7x07ko8n

The call from the onBlur seems to keep the initialValue and not the updated one
I will take a look and try to identify the problem.

Thanks

**Comment by SimonFc** [comment]
Hmm I think I have found the reason for this behavior. On each re-render of the WysiwygEditorHooks component new event handlers for `onEditorChange` and `onBlur` are created being, each of which captures the scoped `editorState` variable.

Due to an implementation detail in tinymce-react the `onEditorChange` handler passed through props to the tinymce-react component is being used by reference. That means that every time tinymce-react calls `onEditorChange` it'll in effect call whatever is the newest handler from the last render of your WysiwygEditorHooks component. Probably what's expected.

The `onChange` handler on the other hand, due to the implementation detail in tinymce-react, is always referencing the original handler provided to `onChange`. Hence each call to the `onChange` handler by the tinymce-react component is being called repeatedly with the original (stale) editorState variable. Probably not what's expected.

**Comment by SimonFc** [comment]
A fix for this is out on @3.3.0. Let me know if you have any further issues!

**Comment by Aldorus** [comment]
Look solved, thank you very much

**Comment by nikitapavets** [comment]
@SimonFc Thank you very much!
