### ISSUE TITLE
Autosave restore when empty not working

### ISSUE THREAD

**Issue by vctormb** [tinymce/tinymce-react#66]
I know that there's a new [merge](https://github.com/tinymce/tinymce/issues/4274) to make `autosave_restore_when_empty` work properly, but when I'm using with React it doesn't work. 

Is it needed to update some dependencies in this `tinymce-react` project?

**Comment by SimonFc** [comment]
Hi, I think it'll work if you set the id property on the react component to something static or by setting the [autosave_prefix](https://www.tiny.cloud/docs/plugins/autosave/#autosave_prefix) to something which does not use the id property. The reason for this is because the id of the react component is randomly generated if not assigned, and this id is then used by the autosave plugin when generating the key to use for localStorage.

I'll close this now but let me know if you encounter any more issues!
