### ISSUE TITLE
How to Integrate Annotation library

### ISSUE THREAD

**Issue by kolaarunkumar** [tinymce/tinymce-react#70]
I'm trying to integrate tinymce-react into my react APP and I want to use Annotation feature, Can you help me how to integrate Annotation plugin and can you please give me Idea about pricing also, I want to use Annotations without tinymce cloud.

**Comment by SimonFc** [comment]
Hi,
The annotations feature of Tiny is a part of the core which means that it's free. (It used to be a plugin in the past) I see now that the [documentation](https://www.tiny.cloud/docs/advanced/annotations/) is a bit of since it mentions "plugin" so that is something we'll have to fix although the functionality described should be correct.
```
<Editor
  init={{
    setup(editor) {
      // Setup the annotator here
    }
  }}
/>
```
It's possible to self-host our [premium plugins](https://apps.tiny.cloud/product-category/tiny-self-hosted-extensions/) as well if you want to avoid using Cloud.

I'll close this issue not but let me know if you encounter any obstacles with the docs for the annotator and I'll see if I can help you!
