### ISSUE TITLE
how to change language

### ISSUE THREAD

**Issue by gcrtime** [tinymce/tinymce-react#71]
My project is a ‘react + TS’ project.Now.I want to use tinymce-react,But how to change the language.I can't put my Chinese package in the project，because no'/lang/'path，No path is possible.So I use a cdn address,but it's only half effective,so sad,who can resolve this problem?
MAYDAY

**Comment by SimonFc** [comment]
I'm closing this one since we already had a thread going on over here: https://github.com/tinymce/tinymce-angular/issues/72

We'll look into extending the documentation of all integrations(React, Angular and Vue) so it's possible that we'll include something about loading language packs as well. In the end, this is an issue that's very much related to your project setup like I mentioned so without knowing exactly what it looks like for you it will be difficult to help. I hope it's going to work out for you!
