### ISSUE TITLE
How to load external stylesheet into Editor iframe

### ISSUE THREAD

**Issue by kolaarunkumar** [tinymce/tinymce-react#72]
I'm trying to tool-tips when user clicks on the annotation text, I have return one stylesheet for that but I'm not able to load that stylesheet because of Iframe I think. I tried in many ways.

`$('#tox-edit-area__iframe').contents().find("body").append($('<link rel="stylesheet" type="text/css" href="./../app.css">'));`

And also I tried to add from content like

```
this.setState({
content = "<link rel="stylesheet" type="text/css" href="./../app.css"><div>some text</div>"
})
```
In the above code div is rendered but styleSheet is not rendered.

using `content_css` I tried to load app.css of my react project
```
.init({
    content_css : "App.css"
});
```

Above three ways not worked for me 

Can you please help me how to add external styles

**Comment by SimonFc** [comment]
You're right about the issue with the iframe so the `content_css` option exists exactly because of this. The issue you have with loading your content css though is most likely one with your project setup so unfortunately it is difficult for me to say anything certain about what you should do. You should see a message about tiny failing to load the content css from path "something...App.css" so it's all about making sure that it's actually provided.

A second option for you would be to use [content_style](https://www.tiny.cloud/docs/configure/content-appearance/#content_style) instead. Let me know if you got any questions!
