### ISSUE TITLE
Problem with page integrations/react.md

### ISSUE THREAD

**Issue by jayenashar** [tinymce/tinymce-react#80]
> *affected page: https://www.tinymce.com/docs/integrations/react/*

Could you please add a mechanism that doesn't use your server in a blocking fashion?  Either how to use the `tinymce` npm module, or how to load tinymce asynchronously (bonus points if I can render a textarea while waiting for tinymce to load).

I tried to implement the latter, but somehow using this to inject the script caused it to be `window.tinyMCE` instead of `window.tinymce` and so tinymce-react didn't find it.

**Comment by SimonFc** [comment]
@jayenashar Do you mean that the script execution is being blocked? When you're using Cloud TinyMCE is loaded asynchronously so that shouldn't happen.

It was a long time since you opened the issue and tinymce-react have been updated since. I think the readme and docs are sufficient in explaining how to load tinymce but let me know if you think there are any further improvements that can be done.

**Comment by jayenashar** [comment]
I mean that a `<script>` tag is used without `async` and so it blocks the rest of the page from loading.

It's not on the linked page anymore, but I see on https://www.tiny.cloud/docs/cloud-deployment-guide/editor-and-features/#step1insertthetinycloudscripttagintothewebpage there is a `<script>` tag without `async`.

**Comment by SimonFc** [comment]
It is true that the script inserted by tinymce-react don't have the async attribute set but that's not needed since it's [inserted dynamically](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#Attributes), hence it will load asynchronously.

I'm not sure if the async attribute should be set on the example on the docs page. Any script executed directly after the fetch using tinymce would fail since tinymce wouldn't be defined. I think it would be best to have that example be as simple as possible. Thoughts?

**Comment by jayenashar** [comment]
yes, i agree there should be a simple example and that one is fine.

i recall i had issues using imported modules, as it was written in the docs at the time, so i had to use the script method.  i did eventually sort out my import issues and went back to that.

now `Editor` will load it for me, so i think that will work fine and there is no reason to keep this issue open.
