### ISSUE TITLE
Version 4.9.1 - Spellchecker keeps the SuggestionsMenu visible after disabled

### ISSUE THREAD

**Issue by atatwalker** [tinymce/tinymce-react#94]
Tested in Firefox. Click in the spellchecker icon. Press the right click over 'thiz' in order to show the SuggestionsMenu for that misspelled word. Click in the spellchecker icon. Now the spellchecker is disabled but the SuggestionsMenu remains visible.

http://fiddle.tinymce.com/s5gaab

**Comment by SimonFc** [comment]
Hi @atatwalker 
This seems to be fixed in TinyMCE 5, see [fiddle](http://fiddle.tinymce.com/vSgaab/1). TinyMCE 4 will only receive fixes for critical issues and as such this isn't anything we'll fix. (That is, problems which breaks functionality of the editor)

Just as a heads-up, issues with TinyMCE go to the TinyMCE [repository](https://github.com/tinymce/tinymce/issues)!
