### ISSUE TITLE
Initialize a plugin inside a React component

### ISSUE THREAD

**Issue by vctormb** [tinymce/tinymce-react#95]
**What is the current behavior?**
I'm trying to initialize a plugin inside a React component to have access to the application data.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/6yz4jzrrxw?fontsize=14) or similar.**
All the comments are inside the TinyMCE file component: https://codesandbox.io/s/tinymce-erssm

**What is the expected behavior?**
To initialize the plugin inside the component, for example, inside an effect and not just outside the component which is not possible to access the application data.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-react`?**
tinymcereact - 3.3.2  
tinymce - 5.1.1

I've never tried to do this in other versions.

**Comment by SimonFc** [comment]
Hi,
Registering your plugin in the setup callback works just fine. [CodeSandbox](https://codesandbox.io/s/tinymce-i849p?fontsize=14) What I think is the issue in your case is that the React effect is running async(delayed slightly) and thus to late for the editor initialization process. So a implementation issue and not one with TinyMCE/tinymce-react

**Comment by mikedloss** [comment]
@SimonFc I'm trying to consolidate 2 responses from you, just so I understand what to do...

In your CodeSandbox link above you used the `setup` key inside of `init`. In #16 you mention in the [last comment](https://github.com/tinymce/tinymce-react/issues/16#issuecomment-485925365) to just use `tinymce.PluginManager.add('customPlugin', (editor) => { /* Do stuff here */ });`. Whenever I do that, I am getting this error:

```
GET https://cdn.tiny.cloud/1/API_KEY/tinymce/5.0.14-54/plugins/example/plugin.min.js net::ERR_ABORTED 404
e.loadScript @ tinymce.min.js:9
Failed to load plugin: example from url plugins/example/plugin.min.js
```

(I am using the code from [this](https://www.tiny.cloud/docs/api/tinymce/tinymce.plugin/) example with no modification)

Is there one definitive way to add custom plugins? All I'm doing, alongside the code snippet above, is adding `example` to my list of plugins, and receiving that error.

**Comment by SimonFc** [comment]
@mikedloss There're many ways to add plugins! So I think that the main confusion comes from the distinction between the tinymce global and one (or more) editor instances.

In vctormb's [example](https://codesandbox.io/s/tinymce-erssm) he's self-hosting so he'll load tinymce which will create the tinymce global:
```import tinymce from "tinymce/tinymce";```

It'll then be possible for him to add new plugins to the plugin manager by using
```tinymce.PluginManager.add("my-example-plugin", function (editor) { /* ... */ });```

This plugin will then be available to ALL editor instances henceforth
```
<Editor
  init={{
    plugins: ["my-example-plugin"]
  }}
/>
```

Of course, if you don't self host the tinymce global wont be available until the tinymce-react component has loaded since it'll load tinymce from a cdn.

Judging by your error it seems like you failed to register your plugin with the PluginManager before the editor is initialized (but after the tinymce global had been loaded which is good) Where are you currently adding your plugin?

**Comment by mikedloss** [comment]
@SimonFc that sounds all like where my mind was leading me yesterday 😬Yeah we aren't self hosting, honestly all I've done so far was just install `@tinymce/tinymce-react` into my project and am just using it inside of a functional component. I was trying to create / initialize the plugin above the rendered component (so hoisted above what React is handling), and was looking at `window.tinymce` to do what I want. I keep finding that that tinymce object exists, it's just I kept getting that error.

More specifically, I was using that tinymce code snippet inside of this code block:

```
import { Editor as TinyMCE } from '@tinymce/tinymce-react';

if (window && window.tinymce) {
  const { tinymce } = window;
  tinymce.PluginManager.add('example', (editor, url) => ...more code goes here);
}

// ...later in the same file

const Editor = (props) => {
  return (
    <TinyMCE apiKey="api-key" {...props} />
  )
}
```

**Comment by SimonFc** [comment]
Yeah at that point in time the TinyMCE global doesn't exist since it's being fetched and initialized from the cdn once the tinymce-react component initializes, not before. In such cases you can do something like [this](https://codesandbox.io/s/tinymcereact-463h6?fontsize=14&hidenavigation=1&theme=dark).

An alternative, if you prefer your current style, is to load TinyMCE manually from the cdn before your functional component initializes. Either by including the a script tag as described [here](https://www.tiny.cloud/docs/quick-start/#step1includethetinymcescript) or perhaps even do it programmatically as we're doing [here](https://github.com/tinymce/tinymce-react/blob/master/src/main/ts/ScriptLoader.ts).

Hope this helps!
