### ISSUE TITLE
How do I load self-hosted tinymce lib with this package?

### ISSUE THREAD

**Issue by ahungry** [tinymce/tinymce-react#96]
I would like to run a self-hosted tinymce, and not the one served from the tiny.cloud CDN.

Is there a config or setting option/guide to do this?

**Comment by ahungry** [comment]
Scanning the code, it seems if window.tinymce is defined, it may not load from the CDN?

**Comment by SimonFc** [comment]
Yeah you're on the right track, if TinyMCE is available in the global scope it'll use that version and not load it from the CDN. You can read more about how to do that in [Advanced installation choices](https://www.tiny.cloud/docs/general-configuration-guide/advanced-install/). I'll close since this isn't an issue with tinymce-react but let me know if you got any questions.
